### ISSUE TITLE
Functions must return DataFrames based on flat proxy variables (now a stub)

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/make-xls-model#1]
https://github.com/epogrebnyak/make-xls-model/blob/master/data_source.py#L61
https://github.com/epogrebnyak/make-xls-model/blob/master/data_source.py#L20

**Comment by gabrielelanaro** [comment]
Is this the kind of dataframe output you expect?

```
------ Data:
time            2013          2014
prop                              
GDP     66190.119920  71406.399200
GDP_IP    105.046748    107.194189
GDP_IQ    101.340798    100.640486
```

**Comment by epogrebnyak** [comment]
Actually no... In function todo commment there is an example of expected dataframe:

```
#todo: must return a dataframe based on *controls_proxy*
    #z = {'GDP_IP' : [95.0, 102.5],
    #     'GDP_IQ' : [115.0, 113.0]}   
    #return pd.DataFrame(z, index=[2015, 2016])
```

In commit c87a5572caedafc6975958a5cf6dd27356dc9c50 added  check_get_controls_as_dataframe(): as a formal 'doctest' test to be passed.

**Comment by epogrebnyak** [comment]
Same story about `get_historic_data_as_dataframe()` - it actually has retruning an expected value before you changed it. Now also has a check `check_get_historic_data_as_dataframe()` via commit below.

**Comment by gabrielelanaro** [comment]
@epogrebnyak Now the test passes, tell me if you need additional changes

**Comment by epogrebnyak** [comment]
Solved:

```
>>> get_sample_controls_as_dataframe()
      GDP_IP  GDP_IQ
2015    95.0     115
2016   102.5     113
>>> get_sample_historic_data_as_dataframe()
              GDP      GDP_IP      GDP_IQ
2013  66190.11992  105.046748  101.340798
2014  71406.39920  107.194189  100.640486
```

**Comment by epogrebnyak** [comment]
As works now: `prop` and `time` labels appear in df listing, but tests pass.

```
------ Historic data as df:
prop          GDP      GDP_IP      GDP_IQ
time
2013  66190.11992  105.046748  101.340798
2014  71406.39920  107.194189  100.640486

------ Control parameters as df:
prop  GDP_IP  GDP_IQ  is_forecast
time
2015    95.0     115            1
2016   102.5     113            1
```
