### ISSUE TITLE
equation not writing a formula for a variable (['profit', 10.0, '', '', '', ''],)

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/make-xls-model#10]
we have an equation for 'profit = avg_credit \* credit_ir - avg_deposit \* deposit_ir + liq \* liq_ir',
but final result is  ['profit', 10.0, '', '', '', ''],

`python mxm.py spec2.xls`, part of output to screen:

```
***** Step 3/4
Done creating 'wb_array'
array([['', '2014', '2015', '2016', '2017', '2018'],
       ['credit', 115.0, '=B2*C9', '=C2*D9', '=D2*E9', '=E2*F9'],
       ['liq', 20.0, '=C2*C14', '=D2*D14', '=E2*E14', '=F2*F14'],
       ['capital', 30.0, '=B4', '=C4', '=D4', '=E4'],
       ['deposit', 90.0, '=B5*C10', '=C5*D10', '=D5*E10', '=E5*F10'],
       ['profit', 10.0, '', '', '', ''],  # <<<<<< PROBLEM SEEN HERE
       ['acc_profit', 5.0, '=B7+B6', '=C7+C6', '=D7+D6', '=E7+E6'],
       ['fgap', 0.0, '=C15-C4-C6-C5-C7', '=D15-D4-D6-D5-D7',
        '=E15-E4-E6-E5-E7', '=F15-F4-F6-F5-F7'],
       ['credit_rog', 0.0, 1.15, 1.15, 1.15, 1.15],
       ['deposit_rog', 0.0, 1.1, 1.1, 1.1, 1.1],
       ['liq_ir', 0.0, 0.02, 0.02, 0.02, 0.02],
       ['credit_ir', 0.0, 0.12, 0.12, 0.12, 0.12],
       ['deposit_ir', 0.0, 0.06, 0.06, 0.06, 0.06],
       ['liq_to_credit', 0.0, 0.2, 0.2, 0.2, 0.2],
       ['ta', 135.0, '=C2+C3', '=D2+D3', '=E2+E3', '=F2+F3']], dtype=object)
```

**Comment by gabrielelanaro** [comment]
I am looking into this issue: the problem seems related to the fact that avg_credit does not appear in variables_dict and the formula parser fails silently with KeyError.

https://github.com/epogrebnyak/make-xls-model/blob/master/xl_fill.py#L157-L181

I believe columns are read from "format", I tried adding avg_credit there but then I get another error. I believe something must be changed in the input file.

**Comment by epogrebnyak** [comment]
I see it now - the variables_dict must contain all vars including:
- variables from 'data_df'
- variables from 'control_df'
- newly created variables that appear on the left side of equation in formulas (eg 'avg_credit'). 

Writing this for reference, will update what the fix is.
