### ISSUE TITLE
Suggested feature: dataset -> data + controls conversion on sheets

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/make-xls-model#18]
'Dataset' sheet:
![image](https://cloud.githubusercontent.com/assets/9265326/9038885/76bd0b72-3a00-11e5-8113-bd19df492258.png)
- All non-empty cells where is_forecast == 0 go to 'data' sheet
- All non-empty cells where is_forecast == 1 go to 'controls' sheet

Suggested key: `-D`.

Additional: maybe allow data not to be covered by equations - write to separate block on 'model' sheet.

**Comment by arwer13** [comment]
- [ ] Historical values of control parameters (for example `EX`, `KWt_CM`) should get into model 
- [ ] N/A shouldn't get into model sheet, replace them with empty cells
- [ ] if value without forecast (like `EU_price`) has no prediction equation it is suspicious, there should a warning

**Comment by epogrebnyak** [comment]
![image](https://cloud.githubusercontent.com/assets/9265326/13338834/1cd27d40-dc35-11e5-8cd9-31716407ea96.png)

![image](https://cloud.githubusercontent.com/assets/9265326/13338880/743e590a-dc35-11e5-923a-b5ab323fece5.png)

[dc.xlsx](https://github.com/epogrebnyak/make-xls-model/files/147482/dc.xlsx)

**Comment by epogrebnyak** [comment]
I see there are two problems to be solved about parsing 'dataset' into 'data' and 'controls':

##Problem 1. Which lines are 'data' and which are 'controls'?

I think this is best detected by formulas in cells. In 
[money_current.xls](https://github.com/epogrebnyak/make-xls-model/blob/master/make_xls_model/examples/money_current.xls?raw=true)
on sheet 'Схема 1' lines above 105 are 'controls' and below 105 are 'data'. 
In last column all 'data' cells have formulas with references to the current sheet, this should be a qualifing criteria for 'data'. 

Maybe there must a column 'Type of variable'  in 'dataset' sheet with three values 'data', 'control', 'undecided', similar to example in comment above. 

##Problem 2. Where does historic observation end and forcast start? 

Easiest way is to add 'is_forecast' variable to 'controls'.

**Comment by arwer13** [comment]
But, for example rows 87 and 109 both have only formulas with references 
to the current sheet in their cells?

**Comment by epogrebnyak** [comment]
`109`: =O91*(O125+O127) is legitimate 'data' forecast formula.
`87` is anomaly, it is computed, but never used on this sheet.  But even if it goes to 'data', this is not a big problem, should be fixed manually.   

I suggest however 'dataset' parser works in two stages: 
1. based on the formula rule "Type of variable" column can is filled (first step), 
2. based on this column lines  go to 'data' and 'controls' (second step). 

Between first and second steps can review codes manually, if needed.

**Comment by arwer13** [comment]
Can we always say, that the first forecast year is the first year for which there is a row with no value in this year?
If yes, is it convenient to do this ways instead of using additional `is_forecast` row?

**Comment by arwer13** [comment]
I started `dataset_sheet` branch, no actual code yet, just playground in separate file. There is version 1 testing `dataset` sheet in examples/spec_dataset.xls

**Comment by epogrebnyak** [comment]
> Can we always say, that the first forecast year is the first year for which there is a row with no value in this year?
- better require `is_forecast` row explicitly, because in actual file all vallues are filled for all years
- example: in _money_current.xls_ all values are filled up, both for control and for forecastable data

**Comment by epogrebnyak** [comment]
_spec_dataset.xls_ if fine to start with, but in actual file (like \* money_current.xls*) to be parsed there will be no blanks in data.

**Comment by arwer13** [comment]
Minimal `dataset` sheet support added in 10c1b9478970910fd6e736c5f62127f618e8bc7a
Need to be refactored. I'm going to do it when full `dataset` parsing is implemented.

**Comment by arwer13** [comment]
> if value without forecast (like EU_price) has no prediction equation it is suspicious, there should a warning
> It's already implemented, user gets

```
ValueError: All data variables must be covered by equations.
Not covered: tap
```

**Comment by arwer13** [comment]
This version still needs some refactoring, but it seems to be ready to be played with (diff: https://github.com/epogrebnyak/make-xls-model/commit/d687353934f9f5df11bf9b319c2f7c3e58336029):
https://github.com/epogrebnyak/make-xls-model/tree/dataset_to_other_sheets

**Comment by epogrebnyak** [comment]
- seems to work with `python ..\model.py -D money_current.xls`
- changed `.` for `_` in variable names in money_current.xls - opened an issue #47 about excluding `.` in variable names 
- perhaps `-D` key should only split 'dataset' sheet, but not make model (see issue #46)

**Comment by epogrebnyak** [comment]
Dataset splitting can also be invoked by `examples/money_current.bat`

**Comment by epogrebnyak** [comment]
@arwer13: suggest we move on to #46 (cli change) and #29 (code refactoring), this seems working. Please merge or PR this branch to master and kill inactive inactive branches in the repo (for clarity).
