### ISSUE TITLE
Testable xlsx files from R solver

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/make-xls-model#20]
1. Add sheets (`data`, `formulas``,`controls`and`model```) to xlsx files + move data to these sheets
2. Run mxm.py over files, add these files to examples
3. Possibly store in .xls, not .xlsx

Files:
- [bm1](https://github.com/epogrebnyak/make-xls-model/files/136067/bm1_balance_model.xlsx)
- [bm2](https://github.com/epogrebnyak/make-xls-model/files/136068/bm2_value_only_bank_sector.xlsx)

**Comment by arwer13** [comment]
Done with bm1, it seams fine, but I'm not sure about bm2, please check it.
[bm1_balance_model.xlsx](https://github.com/epogrebnyak/make-xls-model/files/139659/bm1_balance_model.xlsx)
[bm2_value_only_bank_sector.xlsx](https://github.com/epogrebnyak/make-xls-model/files/139660/bm2_value_only_bank_sector.xlsx)

Should them be .xls or .xlsx? No problems with saving them as .xls.

**ADDED**: No problems with xlsx processing occurred.

**Comment by epogrebnyak** [comment]
Will check, xls is fine, many thanks for keeping up pace with the project

21 февр. 2016 г. 5:58 PM пользователь "Veremeenko Artyom" <
notifications@github.com> написал:
