### ISSUE TITLE
FOR REVIEW - Add ref_file.xls to examples

### ISSUE THREAD

**Issue by arwer13** [epogrebnyak/make-xls-model#23]

**Comment by arwer13** [comment]
`ref_file.xls` copied to `examples` folder and  edited to match the format of other example-files:
- added and filled `names` sheet
- `result` sheet renamed to `model`
- `forecast` years changed, to form continuous timeline along with `data` years

Now

```
python mxm.py examples\ref_file.xls -M
```

runs smoothly.

What ref_file.xls is intended for? Minimal working example? I'd like to give it a better name.

**Comment by epogrebnyak** [comment]
`ref_file.xls` is a minamal working example, but it is also generetated by a [script](https://github.com/epogrebnyak/make-xls-model/blob/master/make_xls_model_test/data_test.py) that does a self-check.

Similar things was done in https://github.com/epogrebnyak/make-xls-model/blob/master/make_xls_model/test/test_make_model.py for `spec.xls`

Need to brush up these examples (they were written at different time with similar intent): put them in one place and describe what they are doing. parts of this code will later become unittests.

**Comment by epogrebnyak** [comment]
Moved code generating `ref_file.xls` to https://github.com/epogrebnyak/make-xls-model/tree/master/make_xls_model/orphan_files
