### ISSUE TITLE
Ugly unfilled historic control values

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/make-xls-model#26]
![image](https://cloud.githubusercontent.com/assets/9265326/13268995/907984be-da96-11e5-93ed-ef80c7724cd8.png)

May want to keep 'data' and 'controls' together on one sheet, this enbles to see historic values for control parameters, but must think of a wat to separate data lines and control lines on that new combined sheet.

**Comment by epogrebnyak** [comment]
See also #18 on that. 

Current thought: may have both data and controls on one sheet + distinguish controlds and data the following way: whatever on the left side of equations is data, all other lines are controls. 

In our terms data is everything we intend forecast.

**Comment by arwer13** [comment]
`nan` values are written as empty strings: e17a9f552ab2d67f8d00a5e3ae0573496d5e2479
