### ISSUE TITLE
Build a model for money_current.xls

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/make-xls-model#42]
[money_current.xls](https://github.com/epogrebnyak/make-xls-model/blob/master/make_xls_model/examples/money_current.xls?raw=true)

**Comment by arwer13** [comment]
I have too many questions about how to convert `Схема 1` sheet to `datasheet`. Although we have discussed a lot, it's still unclear for a person who doesn't now your work's specificity what, for example should be done with rows without "variable" names in B column, or with the cells containing references to another sheets and so on.

**Comment by epogrebnyak** [comment]
Variable labels should be added manually. There also can be a column with
labels 'data' and 'control', based on this column a procedure shoukd move
line to respective sheet.
29 февр. 2016 г. 9:19 пользователь "Veremeenko Artyom" <
notifications@github.com> написал:

**Comment by epogrebnyak** [comment]
Alternatively one can consider that moving lines to data and controls sheet
is a manual task.
2 марта 2016 г. 9:17 пользователь "Evgeny Pogrebnyak" <
e.pogrebnyak@gmail.com> написал:

**Comment by arwer13** [comment]
Maybe close it as it was absorbed by https://github.com/epogrebnyak/make-xls-model/issues/18 ?
