### ISSUE TITLE
review and comment eqcell_core.py

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/make-xls-model#5]
https://github.com/epogrebnyak/make-xls-model/blob/master/eqcell_core.py

This file is a piece of https://github.com/epogrebnyak/eqcell repo - torn down to produce a valid Excel reference containign formulas. It has many workarounds and not always clear whether variable is a list, dist, symoy expressions, etc. I made it work with a few alterations/plugs in code, but it passed a docopt text for `check_parse_equation_to_xl_formula()`

why use it:
- it works
- it can not just substitute something in formula, but also evaluate a formula

why not use it:
- it is a bit of spaghetti
- it is likely to fail if formula has some Excel functions in in, espacially Russian, eg '=ЕСЛИ(...)'

Todo: comment this discussion +  mark unclear things in code.

**Comment by epogrebnyak** [comment]
eqcell_core.py also condenses formula from `a /100 * b /100` to `a * b / 10000`

**Comment by epogrebnyak** [comment]
*it passed doctest test

**Comment by gabrielelanaro** [comment]
I think there are quite a bit of useful functions (and structure), so we should keep it. As you mentioned in the comment, the parser/exection scheme is simplistic and could fail when using functions.

My suggestion is to write an explicit parser for equations so that, for example we can map excel expressions (EXP(), LOG(), SQRT() etc..)  which are in russian, to the equivalent python/sympy expressions. In this way, we can also give explicit error messages. I believe the simplification part wouldn't need any change.

**Comment by epogrebnyak** [comment]
What about this: if we dont not evaluate exprerssion inside python, all we need is substitute 'x(t)'-like elements with 'A1'-like elements. For ease of use can require variables to be be x[t] with square brackets. This can be a simpel parser of equation text string that:
- searches for [(*)] element, (*) is time index expression
- searches for [+-*/^[space][strart of string][something else]]( * )[ where (*) will be variable name. 
- variable name + time index can be translated to to A1 style reference
  Such parsing is similar in nature to one in linaer matrix wrapper and will preserve formulas in string, even if Russian Excel ones. I'd be glad if you can paraphrase the described in this comment more clearly and we can put it as 'todo' for next stage

**Comment by gabrielelanaro** [comment]
Sounds like a good strategy, I'll write the TODO in a comment of eq_cell.parse_equation_to_xl_formula

**Comment by gabrielelanaro** [comment]
I was wondering, in this way however we drop the sympy simplification (all we do is basically replacing time-dependent variables with excel cell names).

For example:

```
'GDP[t-1] * GDP_IP[t] / 100 * GDP_IQ[t] / 100'
```

will give us

```
=D2*E3 / 100*E4 / 100
```

 is that OK?

**Comment by gabrielelanaro** [comment]
@epogrebnyak I wrote the TODO. let me know if that's what you intended

**Comment by epogrebnyak** [comment]
It is wrong approch to modify eqcell_core.py for new algorithm, TODO's relating to new text string parser should not be there, but in a separate file. See below:

## Interface

`get_xl_formula(cell, var_name, formulas_dict, variables_dict)` is interface to current parsing algorithm calling `parse_equation_to_xl_formula`  from `eqcell_core` module. We can split this call into to two options of call:

``` python
###########################################################################
## get_xl_formula - interface to eqcell_core.py and new text parser
###########################################################################

def get_xl_formula(cell, var_name, equations_list, variables_dict):
        # COMMENT - EP:  I consider splitting 'equations_list' into 'formulas_dict' a common task 
        #                for both parsers, but in concept this does not really belong to 'xl_fill.py'
        #                May later move strip_timeindex(str_), test_parse_to_formula_dict() and 
        #                parse_to_formula_dict(equations) to a separate module, callable either by two parsers OR
        #                at stage where we evaluate user-defined input.
        # Additionally:  - we currently do not check formulas: 
        #                   * Only current period vars allowed on left side. Valid: "x(t)= x(t-1)". Not Valid: "x(t+1) = x(t)"
        #                   * All required varables must be covered by formulas
        #                   * What happens if there is a variable that is created from other variables, but not listed in data or controls?
        #                - perhaps it is enough to pass only left-habd side of 'equation_as_dict' further. 
        #                  EP:Done    
        #                - cross-dependencies of 'TIME_INDEX_VARIABLES'       

        formulas_dict = parse_to_formula_dict(equations_list)
        equation_as_dict = formulas_dict[var_name]
        formula_as_string = equation_as_dict['formula']
        return get_xl_formula_sympyparser(cell, var_name, formula_as_string, variables_dict)

def get_xl_formula_textparser(cell, var_name, formula_as_string, variables_dict):
        # interface to new parsing algorithm 
        return None

def get_xl_formula_sympyparser(cell, var_name, formula_as_string, variables_dict):
        """
        cell is (row, col) tuple
        varname is like 'GDP'
        formula_as_string is 'x(t-1) + 1'
        variables_dict is like {'GDP': 2} - shows at which row the var is        
        """         
        try:
            time_period = cell[1]            
            return parse_equation_to_xl_formula(formula_as_string, variables_dict, time_period)
        except KeyError:
            return ""        
```

Given this interface and comments we have following tasks outstanding:
1. undo recent TODOs related to new parsing algorithm you have made in eqcel_core.py. I suggest working on textparser in new py file. 
2.  write pseudocode/todos for get_xl_formula_sympyparser(cell, var_name, formula_as_string, variables_dict) based on original proposal in this issue to text string parser
3.  separate task is cleaning up eqcell_core - it needs cleaning up (e.g. get_xl_col_litteral is a stub + some earlier comments marked as 'GL') in fields not related to new algorithm. 

Wait a bit for commits to update my files, done through web browser. 
EP: Files now updated, see if python xl_fill.py runs OK on your machine.

**Comment by gabrielelanaro** [comment]
xl_fill works OK on my machine.

What I'll do next is:
- [x] create new module formula_parser.py where we will put the new parser code and relative TODOs.
- [x] fill up the function get_xl_formula_textparser to interface with formula_parser.py
- [x] revert changes to eq_cell.py

**Comment by epogrebnyak** [comment]
On second point - I consider inteface function fixed, not to be changed now. It has to symmetric to a call from eqcell_core

**Comment by epogrebnyak** [comment]
On third point - can make a list of eqcell's own to do's for cleanup

**Comment by epogrebnyak** [comment]
On your #2, just keep it as a to do , do not fill it now

**Comment by gabrielelanaro** [comment]
For first point you can review this code:
https://github.com/epogrebnyak/make-xls-model/blob/master/formula_parser.py#L3-L19

I have a question: should we use square or round brackets? Square brackets are easier to integrate, because if we use round brackets we may get confused with function calls, such as SUM(). But if you like round brackets more, we can always ignore expressions that do not contain `t` between brackets.

I also reverted changes to eq_cell.py.
I have a question regarding cleanup: You want me to make the implementation more robust, refactoring, or only to apply cosmetic changes?

**Comment by epogrebnyak** [comment]
Please see my comments in  https://github.com/epogrebnyak/make-xls-model/blob/master/formula_parser.py

For eqcell_core.py lets do something cosmetic (new text string parser will be used in the program, eqcell_core.py to be depreciated form this project)

**Comment by epogrebnyak** [comment]
as for eqcell_core.py - I restpred it working and made it pass a test similar to formula_parser in 9ad6e6e285efc1a7d0e4090d69d927244741927b, should work now

there is one TODO is eqcell_core.py - see around https://github.com/epogrebnyak/make-xls-model/blob/master/eqcell_core.py#L111-L113

**Comment by gabrielelanaro** [comment]
Great, I can work on that tomorrow. I'll write to you when I'm done with the TODOs

**Comment by epogrebnyak** [comment]
Please work on https://github.com/epogrebnyak/make-xls-model/issues/9 first as it is critical. 

This issue is low priority.

**Comment by gabrielelanaro** [comment]
I updated the eqcell_core files with docstrings, I don't have any comments regarding the code itself. I also confirm that it works.
