### ISSUE TITLE
Create get_dataframe_before_equations(data_df, controls_df, var_label_list)

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/make-xls-model#7]
As specified in https://github.com/epogrebnyak/make-xls-model/blob/master/xl_fill.py#L42-L54

**Comment by gabrielelanaro** [comment]
The dataframes passed are:

**\* Array before equations:
data_df

```
prop          GDP      GDP_IP      GDP_IQ
time                                     
2013  66190.11992  105.046748  101.340798
2014  71406.39920  107.194189  100.640486
```

controls_df

```
prop  GDP_IP  GDP_IQ  is_forecast
time                             
2015    95.0     115            1
2016   102.5     113            1
```

But the dataframe returned by _internal_get_dataframe_before_equations is like this:

```
             GDP      GDP_IP      GDP_IQ  is_forecast
2013  66190.11992  105.046748  101.340798          NaN
2014  71406.39920  107.194189  100.640486          NaN
2015          NaN  115.000000   95.000000            1
2016          NaN  113.000000  102.500000            1
```

For example GDP_IP in 2015 corresponds to 115  which is different from the controls_df input (which is 95)

I'm currently returning the "matching" version but that fails some tests so I'm not sure this is right:

```
              GDP      GDP_IP      GDP_IQ  is_forecast
time                                                  
2013  66190.11992  105.046748  101.340798          NaN
2014  71406.39920  107.194189  100.640486          NaN
2015          NaN   95.000000  115.000000            1
2016          NaN  102.500000  113.000000            1
```

**Comment by epogrebnyak** [comment]
There is an error in controls_df. Controls_df shoudl be:
controls_df

```
prop  GDP_IQ  GDP_IP  is_forecast
time                             
2015    95.0     115            1
2016   102.5     113            1
```

**Comment by epogrebnyak** [comment]
It appears that 

`df.columns = var_label_list` 

is just renaming, which is an error. We need subsetting: 

`df [var_label_list]`

**Comment by gabrielelanaro** [comment]
Oh I see I'm sorry, thanks for fixing the bug

**Comment by epogrebnyak** [comment]
No problem, luckily it was detectable. Will push a bigger update soon and close.
